name: Setup
description: Setup node and install dependencies
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      uses: bahmutov/npm-install@v1
