name: Setup
description: Setup node and install dependencies
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      uses: bahmutov/npm-install@v1
