import type { VirtualElement } from '@floating-ui/dom'

export type ReferenceElement = HTMLElement | VirtualElement

export type FloatingElement = HTMLElement

// Using the `__VLS_WithTemplateSlots` type to provide vue component slots type.
// Copied from code generated by Volar.
export type __VLS_WithTemplateSlots<T, S> = T & {
  new (): {
    $slots: S
  }
}
